#################
### AUTOSTART ###
#################

source=~/.config/hypr/programs.conf

# exec-once = $terminal
exec-once = $dock &
exec-once = hyprpaper &
exec-once = waybar &
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = dunst &
exec-once = eww daemon
exec-once = dbus-run-session pipewire
exec-once = wireplumber
exec-once = pipewire-pulse
exec-once = /usr/lib/xdg-desktop-portal-termfilechooser &
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Graphite-blue-Dark"
exec-once = dbus-update-activation-environment --all
exec-once = sudo plymouth quit
