-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- #######################################################################################

-- AUTOGENERATED HYPRLAND CONFIG.

-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.

-- #######################################################################################

require("modules.env")
require("modules.programs")
require("modules.monitor")
require("modules.permissions")
require("modules.lookandfeel")
require("modules.input")
require("modules.bindings")
require("modules.winrules")
require("modules.layerrules")
require("modules.autostart")
