######################
##### Layerrules #####
######################

layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace waybar
layerrule = blur on, match:namespace nwg-dock
layerrule = ignore_alpha 0, match:namespace nwg-dock
layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 0, match:namespace notifications
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0, match:namespace rofi
layerrule = blur on, match:namespace eww-blur
layerrule = ignore_alpha 0, match:namespace eww-blur

