###################
### MY PROGRAMS ###
###################

## System Commands
$confirm = ~/.config/hypr/scripts/confirm.sh

## Window Management
$floating = ~/.config/hypr/scripts/floating.sh
$fullscreen = hyprctl dispatch fullscreen 1
$minimize = ~/.config/hypr/scripts/minimize.sh
$opaque = ~/.config/hypr/scripts/toggleopaque.sh

## Utilities
$clpbrd = cliphist list | rofi -dmenu -p "Clipboard" | cliphist decode | wl-copy
$clrclpbrd = cliphist wipe && notify-send "Clipboard Cleared"
$scrnsht = grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/Screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png | wl-copy

## UI & Layers
$bluetooth = ~/dotfiles/.config/eww/scripts/bluetooth.sh
$ctrlcntr = eww open --toggle control_center
$dock = nwg-dock-hyprland -d -i 30 -hd 0
$dockshow = killall -SIGUSR1 nwg-dock-hyprland
$menu = rofi -show drun
$osd = ~/.config/hypr/scripts/osd.sh
$rofi = pkill rofi || rofi -show drun
$wifi = ~/dotfiles/.config/eww/scripts/wifi.sh

## Apps
$browser = brave
$fileManager = nautilus
$gemini = gtk-launch brave-gdfaincndogidkdcdkhapmbffkckdkhn-Profile_1.desktop  
$terminal = kitty
$whatsapp = gtk-launch brave-hnpfjngllnobngcgfapefoaidbinmjnm-Profile_1.desktop
