[ids]
*

[main]
capslock = backspace
tab = overload(control,tab)
space = overload(symbols,space)
leftshift = overload(shift,esc)

[control]
h = left
j = down
k = up
l = right

[symbols]
capslock = delete
a = [
s = ]
d = {
f = }
g = ~
G = `
h = \
H = |
j = -
k = =
l = +
; = !
m = &
n = *
v = $
c = #
x = @

q = 1
w = 2
e = 3
r = 4
t = 5
y = 6
u = 7
i = 8
o = 9
p = 0

