#!/bin/bash

case "$1" in
    --help|-h)
        echo "theme is written to change system wide theme for" 
        echo "Hyprland-dotfiles-artix by Ayaanfaisaall"
        echo "usage: theme <int>"
        echo ""
        echo "options:"
        echo "  --help      to show this help menu"
        echo "  --ls        to show list of themes"
        echo "examples:"
        echo "  theme 16"
        echo "  theme --ls"
        exit 0
        ;;
    --ls)
        timg --grid=7 --title="%b" "$HOME/dotfiles/.config/hypr/wallpapers/"* 2> /dev/null
        echo " "
        exit 0
        ;;
    *)
        if [[ -z "$1" ]] || [[ ! "$1" =~ ^[0-9]+$ ]]; then
            echo "usage: theme <int>"
            echo "or: theme --help to view options"
            exit 1
        fi
        ;;
esac

no=$1

hyprppr="$HOME/.config/hypr/hyprpaper.conf"
hyprlck="$HOME/.config/hypr/hyprlock.conf"
wybr="$HOME/.config/waybar/config.jsonc"
sddm="/usr/share/sddm/themes/silent/configs/default.conf"

sed -i "s/[0-9]\+\.jpg/$no.jpg/g" "$hyprppr"
sed -i "s/[0-9]\+\.jpg/$no.jpg/g" "$hyprlck"
sed -i "s/[0-9]\+\.jpg/$no.jpg/g" "$sddm"

if [ "$no" -eq 14 ]; then
    sed -i "s/zaailW\.svg/zaail.svg/g" "$wybr"
else
    sed -i "s/zaail\.svg/zaailW.svg/g" "$wybr" &> /dev/null
fi

pkill waybar; waybar &> /dev/null &
pkill hyprpaper; hyprpaper &> /dev/null &

echo "theme: $no applied successfully"
